#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0 on Sun May  4 23:13:00 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from . import extra_widgets as xw
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((620, 250))
        self.SetTitle(u"Excel検証")

        self.status_bar = self.CreateStatusBar(1)
        self.status_bar.SetStatusWidths([-1])

        self.panel = wx.Panel(self, wx.ID_ANY)
        self.panel.SetMinSize((620, -1))

        app_sizer = wx.BoxSizer(wx.VERTICAL)

        input_sizer = wx.StaticBoxSizer(wx.StaticBox(self.panel, wx.ID_ANY, "Input"), wx.VERTICAL)
        app_sizer.Add(input_sizer, 0, wx.ALL | wx.EXPAND, 5)

        v_sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        input_sizer.Add(v_sizer_2, 1, wx.ALL | wx.EXPAND, 5)

        label_3 = wx.StaticText(input_sizer.GetStaticBox(), wx.ID_ANY, "Epub")
        v_sizer_2.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)

        self.epub_selector = xw.DropableFilePickerCtrl(input_sizer.GetStaticBox(), wx.ID_ANY, wildcard="Epub files (*.epub)|*.epub")
        v_sizer_2.Add(self.epub_selector, 1, wx.EXPAND, 0)

        v_sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        input_sizer.Add(v_sizer_1, 1, wx.ALL | wx.EXPAND, 5)

        label_2 = wx.StaticText(input_sizer.GetStaticBox(), wx.ID_ANY, "Excel")
        v_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)

        self.toc_selector = xw.DropableFilePickerCtrl(input_sizer.GetStaticBox(), wx.ID_ANY, wildcard="Excel files (*.xlsx)|*.xlsx")
        v_sizer_1.Add(self.toc_selector, 1, wx.EXPAND, 0)

        app_sizer.Add((20, 10), 0, 0, 0)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        app_sizer.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 5)

        v_sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(v_sizer_5, 1, wx.ALL | wx.EXPAND, 5)

        self.toc_check_button = wx.Button(self.panel, wx.ID_ANY, u"Excel検証")
        v_sizer_5.Add(self.toc_check_button, 1, wx.EXPAND | wx.RIGHT, 5)

        self.panel.SetSizer(app_sizer)

        self.Layout()
        # end wxGlade

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.TocTools = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.TocTools)
        self.TocTools.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    MyApp = MyApp(0)
    MyApp.MainLoop()
